---
title: "Functional vignette to test wrappers for baselinenowcast"
output:
  bookdown::html_vignette2:
    fig_caption: yes
    code_folding: show
    fig_width: 8
    fig_height: 5
pkgdown:
  as_is: true
bibliography: library.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa-numeric-superscript-brackets.csl
link-citations: true
vignette: >
  %\VignetteIndexEntry{Wrapper functions for baselinenowcast}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
# nolint start
# Installing epinowcast
# install.packages(
#  "epinowcast", repos = "https://epinowcast.r-universe.dev"
# ) #nolint
# nolint end
# Load packages
library(baselinenowcast)
library(epinowcast)
library(ggplot2)
library(dplyr)
library(tidyr)
# Set seed for reproducibility
set.seed(123)
```

All the preprocessing to get to the reporting triangle, that will eventually go into the S3 methods I think?
```{r}
nowcast_date <- "2021-08-01"
eval_date <- "2021-10-01"
max_delay <- 30

target_data <- germany_covid19_hosp[location == "DE"][age_group == "00+"] |>
  enw_filter_report_dates(latest_date = eval_date) |>
  enw_filter_reference_dates(
    latest_date = nowcast_date
  )

latest_data <- enw_latest_data(target_data)

observed_data <- enw_filter_report_dates(
  target_data,
  latest_date = nowcast_date
)

pobs <- enw_preprocess_data(
  obs = observed_data,
  max_delay = max_delay + 1
)
reporting_triangle_df <- select(
  pobs$new_confirm[[1]],
  reference_date,
  delay,
  new_confirm
)

reporting_triangle <- reporting_triangle_df |>
  pivot_wider(names_from = delay, values_from = new_confirm) |>
  select(-reference_date) |>
  as.matrix()
```
Take the inputs and use them to configure the defaults (but these can also be args)
```{r}
n_training_volume <- 3 * max_delay
n_history_delay <- as.integer(0.5 * n_training_volume)
n_retrospective_nowcasts <- n_training_volume - n_history_delay
draws <- 1000
```

Estimate and apply delay function
```{r}
point_nowcast_matrix <- estimate_and_apply_delay(
  reporting_triangle,
  max_delay,
  n_history_delay
)
```

Estimate and apply uncertainty function
```{r}
nowcast_draws_df <- estimate_and_apply_uncertainty(
  point_nowcast_matrix,
  reporting_triangle,
  max_delay = max_delay,
  draws = draws
)
```
