#' Generate retrospective reporting triangles
#'
#' This function ingests a list of truncated reporting matrices and iteratively
#'   generates the reporting triangle that would have been available as of the
#'   maximum reference time, working from bottom to top for `n` snapshots.
#'
#' @param trunc_rep_mat_list List of truncated reporting matrices.
#' @inheritParams replace_lower_right_with_NA
#' @returns `rep_tri_mat_list` List of retrospective reporting triangles,
#'   generated by removing the bottom right observations from the truncated
#'   reporting triangle matrices.
#' @importFrom cli cli_abort
#' @export
#' @examples
#' triangle <- matrix(
#'   c(
#'     65, 46, 21, 7,
#'     70, 40, 20, 5,
#'     80, 50, 10, 10,
#'     100, 40, 31, 20,
#'     95, 45, 21, NA,
#'     82, 42, NA, NA,
#'     70, NA, NA, NA
#'   ),
#'   nrow = 7,
#'   byrow = TRUE
#' )
#'
#' trunc_rts <- truncate_triangles(
#'   reporting_triangle = triangle,
#'   n = 2
#' )
#' retro_rts <- generate_triangles(
#'   trunc_rep_mat_list = trunc_rts
#' )
#' retro_rts
#'
#' # With custom structure
#' retro_rts_custom <- generate_triangles(
#'   trunc_rep_mat_list = trunc_rts,
#'   structure = 2
#' )
#' retro_rts_custom
generate_triangles <- function(trunc_rep_mat_list, structure = 1) {
  # Check that input is a list of matrices
  if (!is.matrix(trunc_rep_mat_list[[1]])) {
    cli_abort(
      message = "The elements of `trunc_rep_mat_list` must be matrices"
    )
  }

  results <- lapply(
    trunc_rep_mat_list,
    replace_lower_right_with_NA,
    structure = structure
  )

  return(results)
}
