#' Generate retrospective reporting triangles
#'
#' This function ingests a list of truncated reporting matrices and iteratively
#'   generates the reporting triangle that would have been available as of the
#'   maximum reference time, working from bottom to top for `n` snapshots.
#'
#' @param reporting_triangle_list List of reporting triangle matrices.
#' @inheritParams replace_lower_right_with_NA
#' @returns `rep_tri_mat_list` List of retrospective reporting triangles,
#'   generated by removing the bottom right observations from the truncated
#'   reporting triangle matrices.
#' @importFrom cli cli_abort
#' @export
#' @examples
#' triangle <- matrix(
#'   c(
#'     65, 46, 21, 7,
#'     70, 40, 20, 5,
#'     80, 50, 10, 10,
#'     100, 40, 31, 20,
#'     95, 45, 21, NA,
#'     82, 42, NA, NA,
#'     70, NA, NA, NA
#'   ),
#'   nrow = 7,
#'   byrow = TRUE
#' )
#'
#' trunc_rts <- truncate_triangles(
#'   reporting_triangle = triangle,
#'   n = 2
#' )
#' retro_rts <- generate_triangles(
#'   reporting_triangle_list = trunc_rts
#' )
#' retro_rts
#'
#' # With custom structure
#' retro_rts_custom <- generate_triangles(
#'   reporting_triangle_list = reporting_triangle_list,
#'   structure = 2
#' )
#' retro_rts_custom
generate_triangles <- function(reporting_triangle_list, structure = 1) {
  # Check that input is a list of matrices
  if (!is.matrix(reporting_triangle_list[[1]])) {
    cli_abort(
      message = "The elements of `reporting_triangle_list` must be matrices"
    )
  }

  results <- lapply(
    reporting_triangle_list,
    replace_lower_right_with_NA,
    structure = structure
  )

  return(results)
}


#' Generate a single retrospective reporting triangle
#'
#' This function generates a single reporting triangle by removing the bottom
#'   right observations from a truncated reporting triangle matrix. It is the
#'   singular version of `generate_triangles()`.
#'
#' @param reporting_triangle A single reporting triangle matrix.
#' @inheritParams replace_lower_right_with_NA
#' @returns A single retrospective reporting triangle matrix with NAs in the
#'   appropriate positions.
#' @export
#' @examples
#' triangle <- matrix(
#'   c(
#'     65, 46, 21, 7,
#'     70, 40, 20, 5,
#'     80, 50, 10, 10,
#'     100, 40, 31, 20,
#'     95, 45, 21, NA,
#'     82, 42, NA, NA,
#'     70, NA, NA, NA
#'   ),
#'   nrow = 7,
#'   byrow = TRUE
#' )
#'
#' retro_rt <- generate_triangle(
#'   reporting_triangle = triangle
#' )
#' retro_rt
generate_triangle <- function(reporting_triangle, structure = 1) {
  return(
    replace_lower_right_with_NA(
      reporting_triangle,
      structure = structure
    )
  )
}
